apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: fusionops-api-quick-check
spec:
  metrics:
  - name: error-rate
    interval: 1m
    count: 5
    successCondition: result[0] < 0.01
    provider:
      prometheus:
        address: http://prometheus.monitoring:9090
        query: |
          sum(rate(otel_http_server_request_failed_total{service_name="fusionops-api", version="{{ .Rollout.PodTemplateHash }}"}[1m]))
          /
          sum(rate(otel_http_server_request_duration_count{service_name="fusionops-api", version="{{ .Rollout.PodTemplateHash }}"}[1m]))
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: fusionops-api-full-check
spec:
  metrics:
  - name: latency-p95
    interval: 1m
    count: 5
    successCondition: result[0] < 0.5
    provider:
      prometheus:
        address: http://prometheus.monitoring:9090
        query: |
          histogram_quantile(0.95,
            sum(rate(otel_http_server_duration_bucket{service_name="fusionops-api", version="{{ .Rollout.PodTemplateHash }}"}[1m])) by (le)
          )
