{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fusionops-api
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fusionops-api
                port:
                  number: {{ .Values.service.port }}
    - host: {{ .Values.ingress.previewHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fusionops-api-preview
                port:
                  number: {{ .Values.service.port }}
{{- end }}
